# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sac_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sac_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sac_inference.proto\x12\rsac_inference\".\n\x12ObservationRequest\x12\x18\n\x10observation_data\x18\x01 \x01(\x0c\"4\n\x0e\x41\x63tionResponse\x12\x13\n\x0b\x61\x63tion_data\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2[\n\x0cSACInference\x12K\n\x07Predict\x12!.sac_inference.ObservationRequest\x1a\x1d.sac_inference.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sac_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATIONREQUEST']._serialized_start=38
  _globals['_OBSERVATIONREQUEST']._serialized_end=84
  _globals['_ACTIONRESPONSE']._serialized_start=86
  _globals['_ACTIONRESPONSE']._serialized_end=138
  _globals['_SACINFERENCE']._serialized_start=140
  _globals['_SACINFERENCE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
